const assert = require('node:assert/strict');
const q = require('../brief-quote');
const parse = q.parse;
const price = text => q.estimate(parse(text));
assert.equal(price('패션영상 최종본 5~7분 1캠 원본 20분. 사진은 100%는 아니지만 찾아서 드릴 예정').recommended, 180000);
assert.equal(price('다큐 최종본 15분 1캠 원본 90분').recommended, 400000);
assert.equal(parse('다큐 캠 1개 최종본 15분\n원본은 일정치않습니다\n원본 기존꺼 평균 체크해봐야하는데 2시간은 안나올 것 같습니다!').raw, 120);
assert.equal(parse('다큐 캠 1개 최종본 15분\n원본은 일정치않습니다\n원본 기존꺼 평균 체크해봐야하는데 2시간은 안나올 것 같습니다!').minutes, 15);
assert.equal(parse('원본 1시간 30분 최종본 6분 30초').raw, 90);
assert.equal(parse('원본 1시간 30분 최종본 6분 30초').minutes, 6.5);
assert.equal(parse('원본 60~90분 최종본 10~15분').raw, 90);
assert.equal(parse('원본 60~90분 최종본 10~15분').minutes, 15);
assert.equal(parse('원본 미정 최종본 15분').raw, 30);
assert.equal(parse('패션영상입니다 그리고 5분 ~7분 전후가 될 것 같습니다').minutes, 7);
assert.equal(parse('https://youtu.be/OwwSfFs7E-0').hasConditions, false);
assert.equal(parse('원본 90분').minutes, 10);
assert.equal(parse('캠 3개 최종본 15분').cameras, 3);
assert.equal(parse('컷편집은 이미 되어있고 종편만 20분').scope, 'locked');
assert.equal(parse('컷편집은 안되어있고 원본 편집부터 해야함').scope, 'full');
assert.equal(parse('투캠 최종본 15분').cameras, 2);
assert.equal(parse('사진 없음 자막 제외').photos, 'none');
assert.equal(parse('사진 없음 자막 제외').captions, false);
assert.equal(parse('사진 전부 제공').photos, 'provided');
assert.equal(parse('롱폼 최종본 15분 숏폼 8개').profile, 'general');
assert.ok(parse('롱폼 최종본 15분 숏폼 8개').assumptions.some(a => a.includes('미포함')));
assert.equal(price('2캠 최종본 15분 원본 15분. 축소 편집하실 필요가 없습니다').recommended, 300000);
assert.equal(price('3캠 최종본 15분 원본 15분. 축소 편집하실 필요가 없습니다').recommended, 350000);
const short = price('숏폼 최종본 30초 원본 5분 1캠 수정 0회');
assert.ok(short.recommended >= 30000);
const one = price('숏폼 최종본 60초 1캠 원본 10분 월 10편 수정 2회');
assert.equal(one.minutes, 1);
assert.equal(one.monthlyTotal, one.recommended * 10);
assert.ok(price('다큐 최종본 15분 1캠 원본 120분').recommended > price('다큐 최종본 15분 1캠 원본 60분').recommended);
assert.ok(q.estimate({ ...parse('패션 7분'), minutes: NaN }).error);
assert.ok(q.estimate({ ...parse('패션 7분'), daily: 0 }).error);
assert.ok(q.estimate({ ...parse('패션 7분'), revisions: -1 }).error);
const normal = price('최종본 10분 원본 30분 1캠');
const revised = q.estimate({ ...normal, revisions: 2 });
assert.ok(revised.recommended > normal.recommended);
assert.ok(!q.reply(normal).includes('영업일 내'));
assert.ok(q.reply(normal).includes('가견적'));
assert.equal(normal.items.reduce((s, i) => s + i.amount, 0), normal.recommended);
console.log('PASS free consultation parsing, pricing, scope and capacity checks');
